Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int engineerId)
    {
      bool matches = _db.EngineerMachine.Any(x => x.EngineerId == engineerId && x.MachineId == machine.MachineId);
      if(!matches) {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        if(engineerId != 0)
        {
          _db.EngineerMachine.Add(new EngineerMachine() { MachineId = machine.MachineId, EngineerId = engineerId});
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int machineId)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == machineId);

      return View(thisMachine);
    }

    public ActionResult Edit(int machineId)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == machineId);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int engineerId)
    {
      if(engineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int machineId)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == machineId);
      return View(thisMachine);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int machineId)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == machineId);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddDoctor(int machineId)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == machineId);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
      bool matches = _db.EngineerMachine.Any(x => x.EngineerId == engineerId && x.MachineId == machine.MachineId);
      if(!matches)
      {
        if(engineerId != 0)
        {
          _db.EngineerMachine.Add(new EngineerMachine() { MachineId = machine.MachineId, EngineerId = engineerId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine
@using Factory.Models

<h1> Add an Engineer </h1>
<h4> Adding new Engineer for @Html.DisplayFor(model => model.Name) </h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Add" />
}

<p> @Html.ActionLink($"Back - Machine: {@Model.Name}", "Details", new { machineId = Model.MachineId })</p>
<p> @Html.ActionLink("Back - Show all Engineers", "Index")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine


<h1> Add a new Machine </h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  @Html.Label("Select an Engineer")
  @Html.DropDownList("EngineerId", null, string.Empty)

  <input type="submit" value="Add a Machine" />
}

<p>@Html.ActionLink("Back - Show all Machine(s)", "Index")</p>
<p>@Html.ActionLink("Back - Homepage", "Index", "Home")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine

<h2>Delete this Machine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back - Show all Machine(s)","Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine
@using Factory.Models

<h1> Machine Details - @Model.Name </h1>
<h2> Department: @Model.Description </h2>

@if(@Model.JoinEntities.Count == 0)
{
  <p>No Engineer(s) available</p>
}
else
{
  <h3>Enginner(s):</h3>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Engineer.Name</li>
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a new Engineer", "AddEngineer", new { machineId = Model.MachineId })</p>
<p>@Html.ActionLink("Edit Current Machine's Info", "Edit", new { machineId = Model.MachineId })</p>
<p>@Html.ActionLink("Delete selected Machine", "Delete", new { machineId = Model.MachineId })</p>
<p>@Html.ActionLink("Go Back - View all Machine(s)", "Index")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Machine
@using Factory.Models

<h1> Edit Machine: @Model.Name </h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.Label("Select a Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back - Show all Machine(s)", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}
@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <p>No Machine(s) Available</p>
}

<ul>
  @foreach(Machine machine in Model)
  {
    <li>@Html.ActionLink($"{@machine.Name}", "Details", new { machineId = machine.MachineId })</li>
  }
</ul>

<p>@Html.ActionLink("Add a Machine", "Create")</p> 
<p>@Html.ActionLink("Back - Homepage", "Index", "Home")</p>