Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public string Department { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set;}
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int machineId)
    {
      bool matches = _db.EngineerMachine.Any(x => x.EngineerId == engineer.EngineerId && x.MachineId == machineId);
      if(!matches) {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        if(machineId != 0)
        {
          _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = engineer.EngineerId, MachineId = machineId });
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int engineerId)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(engineer => engineer.EngineerId == engineerId);

      return View(thisEngineer);
    }

    public ActionResult Edit(int engineerId)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == engineerId);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int machineId)
    {
      if(machineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = engineer.EngineerId, MachineId = machineId});
      }

      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Delete(int engineerId)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == engineerId);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int engineerId)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == engineerId);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int engineerId)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == engineerId);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
      bool matches = _db.EngineerMachine.Any(x => x.EngineerId == engineer.EngineerId && x.MachineId == machineId);
      if(!matches)
      {
        if(machineId != 0)
        {
          _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = engineer.EngineerId, MachineId = machineId });
        }
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer
@using Factory.Models

<h1> Add a Machine </h1>
<h4> Adding new Machine for @Html.DisplayFor(model => model.Name) </h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Add" />
}

<p> @Html.ActionLink($"Back - Engineer: {@Model.Name}", "Details", new { engineerId = Model.EngineerId })</p>
<p> @Html.ActionLink("Back - Show all Engineers", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer


<h1> Add a new Engineer </h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Department)
  @Html.TextBoxFor(model => model.Department)

  @Html.Label("Select a Machine")
  @Html.DropDownList("MachineId", null, string.Empty)

  <input type="submit" value="Add an Engineer" />
}

<p>@Html.ActionLink("Back - Show all Engineer", "Index")</p>
<p>@Html.ActionLink("Back - Homepage", "Index", "Home")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer

<h2>Delete this Engineer?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back - Show all Engineers","Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer
@using Factory.Models

<h1> Engineer Details - @Model.Name </h1>
<h2> Department: @Model.Department </h2>

@if(@Model.JoinEntities.Count == 0)
{
  <p>No Machine(s) available</p>
}
else
{
  <h3>Machine(s) to Repair:</h3>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Machine.Name</li>
      @using (Html.BeginForm("DeleteMachine", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a new Machine", "AddMachine", new { engineerId = Model.EngineerId })</p>
<p>@Html.ActionLink("Edit Current Engineer's Info", "Edit", new { engineerId = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete selected Engineer", "Delete", new { engineerId = Model.EngineerId })</p>
<p>@Html.ActionLink("Go Back - View all Engineers", "Index")</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}
@model Factory.Models.Engineer
@using Factory.Models

<h1> Edit Engineer: @Model.Name </h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Department)
  @Html.EditorFor(model => model.Department)

  @Html.Label("Select a Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back - Show all Engineers", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}
@model List<Factory.Models.Engineer>
@using Factory.Models

<h1> Engineers View </h1>
<h3> Current Available Engineer(s): @Model.Count</h3>
@if(Model.Count == 0)
{
  <h5> No Available Engineer(s) </h5>
}
else
{
  <ul>
    @foreach (Engineer engineer in Model)
    {
      <li>@Html.ActionLink($"{@engineer.Name}", "Details", new { engineerId = engineer.EngineerId }) </li>
    }
  </ul>
}

<p>@Html.ActionLink("Add a new Engineer", "Create")</p>
<p>@Html.ActionLink("Go Back Home", "Index", "Home")</p>